### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by NobbZ** [rjanicek/janicek-core-haxe#1]
Hi there!

Could you please give a brief overview of how to use your lib in a haxe project?

I wasn't able to find it on lib.haxe.org, but want to use the one or the other class it provides.

_edit_
I forgot: I'm using haxe3

**Comment by rjanicek** [comment]
-Download the files into a library directory in your project.
-Add the 'src' directory to your project's classpaths.

-Look at the FlashDevelop project (janicek-core.hxproj) or the Haxe build script (build.hxml) to see exaple project structures.

**Comment by NobbZ** [comment]
I will try this out tomorrow.
