### ISSUE TITLE
low entropy seed limits uuids to ~117k

### ISSUE THREAD

**Issue by thomasuster** [rjanicek/janicek-core-haxe#2]
If you seed with Math.random you only get about 117k different seeds. UUID requires seed of about 2^128

https://github.com/rjanicek/janicek-core-haxe/blob/6630d81bc734a8886e0156fd3a95e7dd3104bd0a/src/co/janicek/core/math/RandomCore.hx#L54

**Comment by sharique123** [comment]
UUId is generating lots of duplicate ids.

**Comment by thomasuster** [comment]
I did this...

https://github.com/thomasuster/extension-secureRandom

There's another library that did it much cleaner than I did, but I can't find it at the moment.
